all:
    configuration:
        drm:
            reserve_interpro:
                certifications/AOP/genres/TRANQ/appellations/CDR:
                    mois_duree: 12
                certifications/AOP/genres/TRANQ/appellations/CVS:
                    mois_duree: 18
                certifications/AOP/genres/TRANQ/appellations/CVG:
                    mois_duree: 18
